### ISSUE TITLE
Unable to store puzzle as map in local storage.

### ISSUE THREAD

**Issue by zs-adarsh** [AlvinRamoutar/sudoku-api#12]
Hey,  thanks for this wonderful package.
It works great. But I am having issues using the toMap() method. 
I am trying to store the puzzle object converted to map and then store it in my Hive storage.
It throws the following error: 
Unhandled Exception: HiveError: Cannot write, unknown type: _HashSet<int>. Did you forget to register an adapter?
E/flutter (13804): #0      BinaryWriterImpl.write
package:hive/…/binary/binary_writer_impl.dart:337
E/flutter (13804): #1      BinaryWriterImpl.writeMap
package:hive/…/binary/binary_writer_impl.dart:236
E/flutter (13804): #2      BinaryWriterImpl.write
package:hive/…/binary/binary_writer_impl.dart:333
E/flutter (13804): #3      BinaryWriterImpl.writeList
package:hive/…/binary/binary_writer_impl.dart:223
E/flutter (13804): #4      BinaryWriterImpl._writeList
package:hive/…/binary/binary_writer_impl.dart:389
E/flutter (13804): #5      BinaryWriterImpl.write
package:hive/…/binary/binary_writer_impl.dart:328
E/flutter (13804): #6      BinaryWriterImpl.writeList
package:hive/…/binary/binary_writer_impl.dart:223
E/flutter (13804): #7      BinaryWriterImpl._writeList
package:hive/…/binary/binary_writer_impl.dart:389
E/flutter (13804): #8      BinaryWriterImpl.write
package:hive/…/binary/binary_writer_impl.dart:328
E/flutter (13804): #9      BinaryWriterImpl.writeMap
package:hive/…/binary/binary_writer_impl.dart:236
E/flutter (13804): #10     BinaryWriterImpl.write
package:hive/…/binary/binary_writer_impl.dart:333
E/flutter (13804): #11     BinaryWriterImpl.writeMap
package:hive/…/binary/binary_writer_impl.dart:236
E/flutter (13804): #12     BinaryWriterImpl.write
package:hive/…/binary/binary_writer_impl.dart:333
E/flutter (13804): #13     BinaryWriterImpl.writeFrame
package:hive/…/binary/binary_writer_impl.dart:281
E/flutter (13804): #14     StorageBackendVm.writeFrames.<anonymous closure>
package:hive/…/vm/storage_backend_vm.dart:127
E/flutter (13804): #15     StorageBackendVm.writeFrames.<anonymous closure>
package:hive/…/vm/storage_backend_vm.dart:123
E/flutter (13804): #16     ReadWriteSync.syncWrite.<anonymous closure>
package:hive/…/vm/read_write_sync.dart:26
E/flutter (13804): #17     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (13804): #18     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (13804): <asynchronous suspension>
E/flutter (13804): #19     BoxImpl._writeFrames
package:hive/…/box/box_impl.dart:88
E/flutter (13804): <asynchronous suspension>

The code snippet:
 var mapper = puzzle.toMap();
 Hive.box('lastPlayed').put('puzzleObject', mapper);

Thanks in advance!

**Comment by AlvinRamoutar** [comment]
Hey @zs-adarsh ,

I'm not too familiar with Hive, but it looks like a custom adapter would be necessary for Sudoku API's puzzle object.
https://docs.hivedb.dev/#/custom-objects/type_adapters

You can try to generate an adapter using Hive's adapter generator:
https://docs.hivedb.dev/#/custom-objects/generate_adapter

Otherwise, this is not an issue with sudoku-api. `toMap()` works as expected (try running `/test/serialization_test.dart`).

Let me know if there's any questions.
Thanks!

**Comment by zs-adarsh** [comment]
Adapters are required when we want to store custom class objects directly into hive. Maps should work without adapters.

If not hive, can you suggest some other database which I could use?

**Comment by clragon** [comment]
this problem is caused by the `Cell` class having invalid json serialization methods, where the `toMap` function will include a `HashSet` which isnt allowed. it should instead use a `List`.
this can be fixed by #15.

**Comment by AlvinRamoutar** [comment]
Hey @clragon ,
Thanks for the suggestion and the PR!
I'm not sure why you closed it, want to re-open it so we can get it merged in? :)
Cheers,
Alvin

**Comment by clragon** [comment]
the request gets closed automatically when I deleted my fork of the repo when cleaning up.
feel free to copy the changes for a normal commit.
